# Generated by Django 4.2.5 on 2023-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.URLField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
