# Generated by Django 4.2.5 on 2023-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_category_remove_product_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_url',
            field=models.URLField(default=False, max_length=600),
        ),
    ]
